CREATE TABLE IF NOT EXISTS dokter (
    ID_Dokter CHAR(36) NOT NULL,
    Nama_Dokter VARCHAR(100) DEFAULT NULL,
    Spesialisasi VARCHAR(50) DEFAULT NULL,
    Nomor_SIP VARCHAR(50) DEFAULT NULL,
    Nomor_Telepon VARCHAR(15) DEFAULT NULL,
    Email VARCHAR(100) DEFAULT NULL,
    Status_Aktif TINYINT(1) DEFAULT 1,
    createdAt DATETIME DEFAULT NULL,
    updatedAt DATETIME DEFAULT NULL,
    PRIMARY KEY (ID_Dokter)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci; 