name: Deploy ke Hostinger via FTP

on:
  push:
    branches:
      - main  # Deploy otomatis saat push ke branch main
      - alpha_v1
      - alpha_v2

  workflow_dispatch:  # Opsi trigger manual di GitHub Actions

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Mengambil hanya 2 commit terakhir untuk mempercepat
      
      # Prepare environment files
      - name: Setup env variables
        run: |
          echo "DB_USER=${{ secrets.DB_USER }}" >> .github/env-templates/.env.secret
          echo "DB_PASS=${{ secrets.DB_PASS }}" >> .github/env-templates/.env.secret
          
      # Deploy aplikasi utama via FTP
      - name: Deploy aplikasi via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          local-dir: ./
          server-dir: /
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            README.md
            **/tests/**
            **/.env*
            **/config.env
            **/vendor/**
            **/.idea/**
            **/.vscode/**
            **/.github/env-templates/.env.secret

      # Jalankan script setup via HTTP request (alternatif SSH)
      - name: Trigger environment setup script
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.APP_URL }}/.env-setup/trigger.php
          method: 'POST'
          customHeaders: '{"Authorization": "${{ secrets.DEPLOY_TOKEN }}"}'
          timeout: 10000
          preventFailureOnNoResponse: true
